version: "2"

services:
  web:
    container_name: teste
    image: wordpress:latest
    ports:
      - "80"
    mem_limit: 1024m
    mem_reservation: 128M
    restart: unless-stopped
    volumes:
      - ./public/:/var/www/html
    labels:
      - "traefik.http.routers.teste.rule=Host(`teste.intest.com.br`)"
      - "traefik.http.routers.teste.tls=true"
      - "traefik.http.routers.teste.tls.certresolver=lets-encrypt"
      - "traefik.http.services.teste.loadbalancer.server.port=80"
    networks:
      - "webproxy"

networks:
  webproxy:
    external:
      name: webproxy
